name: Build QA Image
on:
  push:
    branches: ["qa"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & push
        run: |
          SHA7=$(echo "${GITHUB_SHA}" | cut -c1-7)
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/${OWNER_LC}/myapp:dev-$SHA7
          docker build -t $IMAGE .
          docker push $IMAGE
